export const EVENT_TYPES = {
  STUDENT_CHECKED_IN: 'STUDENT_CHECKED_IN',
  DROPOFF_ACKNOWLEDGMENT_SENT: 'DROPOFF_ACKNOWLEDGMENT_SENT',
  DROPOFF_ACKNOWLEDGED: 'DROPOFF_ACKNOWLEDGED',
  DROPOFF_ACKNOWLEDGMENT_FAILED: 'DROPOFF_ACKNOWLEDGMENT_FAILED',
  PICKUP_REQUEST_SENT: 'PICKUP_REQUEST_SENT',
  PICKUP_ACKNOWLEDGED: 'PICKUP_ACKNOWLEDGED',
  PICKUP_ACKNOWLEDGMENT_FAILED: 'PICKUP_ACKNOWLEDGMENT_FAILED',
  STUDENT_CHECKED_OUT: 'STUDENT_CHECKED_OUT',
  DROPOFF_OVERRIDE: 'DROPOFF_OVERRIDE',
  PICKUP_OVERRIDE: 'PICKUP_OVERRIDE',
  ATTENDANCE_CORRECTION: 'ATTENDANCE_CORRECTION',
  SMS_QUEUED: 'SMS_QUEUED',
  SMS_SENT: 'SMS_SENT',
  SMS_FAILED: 'SMS_FAILED',
} as const;

export type EventType = typeof EVENT_TYPES[keyof typeof EVENT_TYPES];

export const DROPOFF_ACK_STATUS = {
  NOT_SENT: 'NOT_SENT',
  QUEUED: 'QUEUED',
  SENT: 'SENT',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  EXPIRED: 'EXPIRED',
  STAFF_OVERRIDE: 'STAFF_OVERRIDE',
} as const;

export type DropoffAckStatus = typeof DROPOFF_ACK_STATUS[keyof typeof DROPOFF_ACK_STATUS];

export const PICKUP_ACK_STATUS = {
  NOT_REQUESTED: 'NOT_REQUESTED',
  LINK_SENT: 'LINK_SENT',
  PICKUP_REQUESTED: 'PICKUP_REQUESTED',
  APPROVED_FOR_RELEASE: 'APPROVED_FOR_RELEASE',
  COMPLETED: 'COMPLETED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  EXPIRED: 'EXPIRED',
  STAFF_OVERRIDE: 'STAFF_OVERRIDE',
} as const;

export type PickupAckStatus = typeof PICKUP_ACK_STATUS[keyof typeof PICKUP_ACK_STATUS];

export const SMS_STATUS = {
  PENDING: 'PENDING',
  SENDING: 'SENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  PERMANENTLY_FAILED: 'PERMANENTLY_FAILED',
} as const;

export type SmsStatus = typeof SMS_STATUS[keyof typeof SMS_STATUS];

export const NOTIFICATION_PROVIDERS = {
  WEB_PUSH: 'WEB_PUSH',
  DEV_OUTBOX: 'DEV_OUTBOX',
  TWILIO: 'TWILIO',
  TELEGRAM: 'TELEGRAM',
} as const;

export type NotificationProvider = typeof NOTIFICATION_PROVIDERS[keyof typeof NOTIFICATION_PROVIDERS];
